global:
  config:
    dbName: app

crunchy:
  enabled: true
  instances:
    replicas: 1  # Single replica for PRs
    dataVolumeClaimSpec:
      storage: 5Gi  # Keep current size
      walStorage: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi

  pgBackRest:
    enabled: false  # Keep disabled for PR environments to save resources

  proxy:
    enabled: true
    pgBouncer:
      replicas: 1
      maxConnections: 25